/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author HP
 */
public class FrmPreguntas extends javax.swing.JFrame {

    /** Creates new form FrmPreguntas */
    public FrmPreguntas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane11 = new javax.swing.JScrollPane();
        txtDiagInfeDere = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDiagSupDere = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtDerecha = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtIzquier = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtExamenActual = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtSuperior = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtDiagInfeIzquier = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtAbajo = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDiagSuperIz = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDiagInfeDere.setColumns(20);
        txtDiagInfeDere.setRows(5);
        jScrollPane11.setViewportView(txtDiagInfeDere);

        txtDiagSupDere.setColumns(20);
        txtDiagSupDere.setRows(5);
        jScrollPane6.setViewportView(txtDiagSupDere);

        txtDerecha.setColumns(20);
        txtDerecha.setRows(5);
        jScrollPane12.setViewportView(txtDerecha);

        txtIzquier.setColumns(20);
        txtIzquier.setRows(5);
        jScrollPane7.setViewportView(txtIzquier);

        txtExamenActual.setColumns(20);
        txtExamenActual.setRows(5);
        jScrollPane13.setViewportView(txtExamenActual);

        txtSuperior.setColumns(20);
        txtSuperior.setRows(5);
        jScrollPane8.setViewportView(txtSuperior);

        txtDiagInfeIzquier.setColumns(20);
        txtDiagInfeIzquier.setRows(5);
        jScrollPane9.setViewportView(txtDiagInfeIzquier);

        txtAbajo.setColumns(20);
        txtAbajo.setRows(5);
        jScrollPane10.setViewportView(txtAbajo);

        txtDiagSuperIz.setColumns(20);
        txtDiagSuperIz.setRows(5);
        jScrollPane5.setViewportView(txtDiagSuperIz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane9))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane12)
                    .addComponent(jScrollPane11))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane10)
                    .addComponent(jScrollPane11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JTextArea txtAbajo;
    public static javax.swing.JTextArea txtDerecha;
    public static javax.swing.JTextArea txtDiagInfeDere;
    public static javax.swing.JTextArea txtDiagInfeIzquier;
    public static javax.swing.JTextArea txtDiagSupDere;
    public static javax.swing.JTextArea txtDiagSuperIz;
    public static javax.swing.JTextArea txtExamenActual;
    public static javax.swing.JTextArea txtIzquier;
    public static javax.swing.JTextArea txtSuperior;
    // End of variables declaration//GEN-END:variables

}
